
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: autotestlab
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1488:5432"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

volumes:
  pgdata:
